// <auto-generated />
using System;
using CineReel.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CineReel.Service.Data.Migrations
{
    [DbContext(typeof(CinereelDbContext))]
    [Migration("20260725142804_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CineReel.Service.Data.Entities.AccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_admin");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("permissions");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("CineReel.Service.Data.Entities.MediaItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DescriptorHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("descriptor_hash");

                    b.Property<string>("DriveKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("drive_key");

                    b.Property<string>("DrivePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("drive_path");

                    b.Property<string>("ImdbId")
                        .HasColumnType("TEXT")
                        .HasColumnName("imdb_id");

                    b.Property<string>("JellyfinPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("jellyfin_path");

                    b.Property<string>("JellyfinState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("jellyfin_state");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastScannedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_scanned_at");

                    b.Property<string>("NfoPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("nfo_path");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("original_title");

                    b.Property<string>("PosterPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("poster_path");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("subscription_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("TorrentPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("torrent_path");

                    b.Property<string>("TrailerPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("trailer_path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("ImdbId")
                        .HasDatabaseName("idx_media_items_imdb");

                    b.HasIndex("JellyfinState")
                        .HasDatabaseName("idx_media_items_jellyfin_state");

                    b.HasIndex("DriveKey", "DrivePath")
                        .HasDatabaseName("idx_media_items_drive");

                    b.HasIndex("SubscriptionId", "DrivePath")
                        .IsUnique();

                    b.ToTable("media_items", (string)null);
                });

            modelBuilder.Entity("CineReel.Service.Data.Entities.PermissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pattern");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Pattern")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("CineReel.Service.Data.Entities.SessionEntity", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_at");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent");

                    b.HasKey("Token");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("idx_sessions_account");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_sessions_expires");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("CineReel.Service.Data.Entities.SubscriptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<string>("DriveKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("drive_key");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset?>("LastDescriptorSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_descriptor_seen_at");

                    b.Property<DateTimeOffset?>("LastRemountedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_remounted_at");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("SubscribedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("subscribed_at");

                    b.HasKey("Id");

                    b.HasIndex("DriveKey")
                        .IsUnique();

                    b.HasIndex("State")
                        .HasDatabaseName("idx_subscriptions_state");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("CineReel.Service.Data.Entities.TorrentFileEntity", b =>
                {
                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_item_id");

                    b.Property<string>("BtState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("bt_state");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Infohash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("infohash");

                    b.Property<long>("StagedBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("staged_bytes");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_bytes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("MediaItemId");

                    b.ToTable("torrent_files", (string)null);
                });

            modelBuilder.Entity("CineReel.Service.Data.Entities.MediaItemEntity", b =>
                {
                    b.HasOne("CineReel.Service.Data.Entities.SubscriptionEntity", "Subscription")
                        .WithMany("MediaItems")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("CineReel.Service.Data.Entities.SessionEntity", b =>
                {
                    b.HasOne("CineReel.Service.Data.Entities.AccountEntity", "Account")
                        .WithMany("Sessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CineReel.Service.Data.Entities.TorrentFileEntity", b =>
                {
                    b.HasOne("CineReel.Service.Data.Entities.MediaItemEntity", "MediaItem")
                        .WithOne("TorrentFile")
                        .HasForeignKey("CineReel.Service.Data.Entities.TorrentFileEntity", "MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("CineReel.Service.Data.Entities.AccountEntity", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("CineReel.Service.Data.Entities.MediaItemEntity", b =>
                {
                    b.Navigation("TorrentFile");
                });

            modelBuilder.Entity("CineReel.Service.Data.Entities.SubscriptionEntity", b =>
                {
                    b.Navigation("MediaItems");
                });
#pragma warning restore 612, 618
        }
    }
}
