// <auto-generated>
//     This code was generated from apps/hyper-agent/test/openapi.snapshot.json
//     by scripts/gen-hyper-agent-client.mjs.
//
//     Do not edit this file manually — it is regenerated on every CI run
//     against the Hyper Agent's OpenAPI contract. A diff in this file
//     means a controller changed without a paired regeneration. Re-run
//     `pnpm regen:hyper-agent-client` locally to update.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace CineReel.Service.Infrastructure.HyperAgent.Generated;

// ── ProblemDetails exception hierarchy ─────────────────────────────────

public abstract class HyperAgentException : Exception
{
    public Uri TypeUri { get; }
    public int StatusCode { get; }
    public string? Detail { get; }

    protected HyperAgentException(Uri typeUri, int statusCode, string? detail, Exception? inner = null)
        : base($"{typeUri} (HTTP {statusCode})" + (detail is null ? "" : ": " + detail), inner)
    {
        TypeUri = typeUri;
        StatusCode = statusCode;
        Detail = detail;
    }
}

public sealed class HyperAgentProblemException : HyperAgentException
{
    public HyperAgentProblemException(Uri typeUri, int statusCode, string? detail)
        : base(typeUri, statusCode, detail) { }
}

public sealed class HyperAgentMissingTokenException : HyperAgentException
{
    public HyperAgentMissingTokenException(Uri typeUri, int statusCode, string? detail)
        : base(typeUri, statusCode, detail) { }
}

public sealed class HyperAgentInvalidTokenException : HyperAgentException
{
    public HyperAgentInvalidTokenException(Uri typeUri, int statusCode, string? detail)
        : base(typeUri, statusCode, detail) { }
}

public sealed class HyperAgentInvalidDriveKeyException : HyperAgentException
{
    public HyperAgentInvalidDriveKeyException(Uri typeUri, int statusCode, string? detail)
        : base(typeUri, statusCode, detail) { }
}

public sealed class HyperAgentDriveNotMountedException : HyperAgentException
{
    public HyperAgentDriveNotMountedException(Uri typeUri, int statusCode, string? detail)
        : base(typeUri, statusCode, detail) { }
}

public sealed class HyperAgentRangeNotSatisfiableException : HyperAgentException
{
    public HyperAgentRangeNotSatisfiableException(Uri typeUri, int statusCode, string? detail)
        : base(typeUri, statusCode, detail) { }
}

public sealed class HyperAgentTransportException : Exception
{
    public HyperAgentTransportException(string message, Exception inner)
        : base(message, inner) { }
}


// ── Models ─────────────────────────────────────────────────────────────

public static class Models
{

    public sealed class HealthResponse
    {}


    public sealed class DriveDescriptor
    {}


    public sealed class HyperdriveEntry
    {}


    public sealed class PeerInfo
    {}


    public sealed class IdentityInfo
    {}


}

// ── Client ────────────────────────────────────────────────────────────

public sealed partial class HyperAgentClient
{
    private readonly HttpClient _http;
    private readonly string _bearerToken;
    private static readonly JsonSerializerOptions JsonOpts = new()
    {
        PropertyNameCaseInsensitive = true,
    };

    public HyperAgentClient(HttpClient http, string bearerToken)
    {
        _http = http ?? throw new ArgumentNullException(nameof(http));
        _bearerToken = bearerToken ?? throw new ArgumentNullException(nameof(bearerToken));
    }

    public async Task<T> SendAsync<T>(HttpRequestMessage req, CancellationToken ct)
    {
        if (!string.IsNullOrEmpty(_bearerToken))
            req.Headers.Authorization = new AuthenticationHeaderValue("Bearer", _bearerToken);

        HttpResponseMessage resp;
        try
        {
            resp = await _http.SendAsync(req, HttpCompletionOption.ResponseContentRead, ct);
        }
        catch (Exception ex)
        {
            throw new HyperAgentTransportException("Hyper Agent unreachable: " + ex.Message, ex);
        }

        if (!resp.IsSuccessStatusCode)
        {
            var problem = await ReadProblemAsync(resp, ct);
            throw MapProblemException(problem, resp.StatusCode);
        }

        var media = resp.Content.Headers.ContentType?.MediaType ?? "";
        if (media.StartsWith("application/json"))
        {
            var raw = await resp.Content.ReadAsStringAsync(ct);
            if (string.IsNullOrWhiteSpace(raw)) return default!;
            return JsonSerializer.Deserialize<T>(raw, JsonOpts)!;
        }
        // Non-JSON (e.g. application/octet-stream for the files endpoint).
        if (typeof(T) == typeof(byte[]))
        {
            var bytes = await resp.Content.ReadAsByteArrayAsync(ct);
            return (T)(object)bytes;
        }
        return default!;
    }

    private static async Task<ProblemEnvelope?> ReadProblemAsync(HttpResponseMessage resp, CancellationToken ct)
    {
        var media = resp.Content.Headers.ContentType?.MediaType ?? "";
        if (!media.StartsWith("application/problem+json")) return null;
        var raw = await resp.Content.ReadAsStringAsync(ct);
        try { return JsonSerializer.Deserialize<ProblemEnvelope>(raw, JsonOpts); }
        catch { return null; }
    }

    private static HyperAgentException MapProblemException(ProblemEnvelope? env, HttpStatusCode status)
    {
        var type = env?.Type is { } t ? new Uri(t) : new Uri("about:blank");
        var detail = env?.Detail;
        if (type.ToString().EndsWith("/missing-token")) return new HyperAgentMissingTokenException(type, (int)status, detail);
        if (type.ToString().EndsWith("/invalid-token")) return new HyperAgentInvalidTokenException(type, (int)status, detail);
        if (type.ToString().EndsWith("/invalid-drive-key")) return new HyperAgentInvalidDriveKeyException(type, (int)status, detail);
        if (type.ToString().EndsWith("/drive-not-mounted")) return new HyperAgentDriveNotMountedException(type, (int)status, detail);
        if (type.ToString().EndsWith("/range-not-satisfiable")) return new HyperAgentRangeNotSatisfiableException(type, (int)status, detail);
        return new HyperAgentProblemException(type, (int)status, detail);
    }

    private static string BuildQueryString(params (string Name, object? Value)[] kvs)
    {
        var sb = new StringBuilder();
        var first = true;
        foreach (var (n, v) in kvs)
        {
            if (v is null) continue;
            if (!first) sb.Append('&');
            first = false;
            sb.Append(n).Append('=').Append(Uri.EscapeDataString(v.ToString() ?? ""));
        }
        return sb.Length == 0 ? "" : "?" + sb.ToString();
    }

    private sealed class ProblemEnvelope
    {
        [JsonPropertyName("type")] public string? Type { get; set; }
        [JsonPropertyName("detail")] public string? Detail { get; set; }
    }



    /// <summary><c>GET /healthz</c></summary>

    public async Task<Models.HealthResponse> HealthControllerHealth(CancellationToken ct = default)

    {

        using var req = new HttpRequestMessage(HttpMethod.Get, $@"
/healthz
");

        return await SendAsync<Models.HealthResponse>(req, ct);

    }



    /// <summary><c>GET /v1/version</c></summary>

    public async Task<object /* { string Name; string Version } */> GetVersion(CancellationToken ct = default)

    {

        using var req = new HttpRequestMessage(HttpMethod.Get, $@"
/v1/version
");

        return await SendAsync<object /* { string Name; string Version } */>(req, ct);

    }



    /// <summary><c>GET /v1/drives</c></summary>

    public async Task<IReadOnlyList<Models.DriveDescriptor>> ListDrives(CancellationToken ct = default)

    {

        using var req = new HttpRequestMessage(HttpMethod.Get, $@"
/v1/drives
");

        return await SendAsync<IReadOnlyList<Models.DriveDescriptor>>(req, ct);

    }



    /// <summary><c>POST /v1/drives</c></summary>

    public async Task<Models.DriveDescriptor> CreateDrive(CancellationToken ct = default)

    {

        using var req = new HttpRequestMessage(HttpMethod.Post, $@"
/v1/drives
");

        return await SendAsync<Models.DriveDescriptor>(req, ct);

    }



    /// <summary><c>DELETE /v1/drives/{key}</c></summary>

    public async Task<object> RemoveDrive(string key, CancellationToken ct = default)

    {

        using var req = new HttpRequestMessage(HttpMethod.Delete, $@"
/v1/drives/{key}
");

        return await SendAsync<object>(req, ct);

    }



    /// <summary><c>GET /v1/drives/{key}/tree</c></summary>

    public async Task DriveTree(string key, CancellationToken ct = default)

    {

        using var req = new HttpRequestMessage(HttpMethod.Get, $@"
/v1/drives/{key}/tree
");

        await SendAsync<Unit>(req, ct);

    }



    /// <summary><c>GET /v1/drives/{key}/entry</c></summary>

    public async Task<Models.HyperdriveEntry> DriveEntry(string key, CancellationToken ct = default)

    {

        using var req = new HttpRequestMessage(HttpMethod.Get, $@"
/v1/drives/{key}/entry
");

        return await SendAsync<Models.HyperdriveEntry>(req, ct);

    }



    /// <summary><c>PUT /v1/drives/{key}/file</c></summary>

    public async Task<object> DriveWriteFile(string key, CancellationToken ct = default)

    {

        using var req = new HttpRequestMessage(HttpMethod.Put, $@"
/v1/drives/{key}/file
");

        return await SendAsync<object>(req, ct);

    }



    /// <summary><c>DELETE /v1/drives/{key}/file</c></summary>

    public async Task DriveDeleteEntry(string key, CancellationToken ct = default)

    {

        using var req = new HttpRequestMessage(HttpMethod.Delete, $@"
/v1/drives/{key}/file
");

        await SendAsync<Unit>(req, ct);

    }



    /// <summary><c>POST /v1/_test/peer</c></summary>

    public async Task TestInjectPeer(CancellationToken ct = default)

    {

        using var req = new HttpRequestMessage(HttpMethod.Post, $@"
/v1/_test/peer
");

        await SendAsync<Unit>(req, ct);

    }



    /// <summary><c>DELETE /v1/_test/peer/{publicKey}</c></summary>

    public async Task TestRemovePeer(string publicKey, CancellationToken ct = default)

    {

        using var req = new HttpRequestMessage(HttpMethod.Delete, $@"
/v1/_test/peer/{publicKey}
");

        await SendAsync<Unit>(req, ct);

    }



    /// <summary><c>GET /v1/files/{driveKey}/{path}</c></summary>

    public async Task ReadFileRange(string driveKey, string path, CancellationToken ct = default)

    {

        using var req = new HttpRequestMessage(HttpMethod.Get, $@"
/v1/files/{driveKey}/{path}
");

        await SendAsync<Unit>(req, ct);

    }



    /// <summary><c>POST /v1/swarm/announce</c></summary>

    public async Task<object> SwarmAnnounce(CancellationToken ct = default)

    {

        using var req = new HttpRequestMessage(HttpMethod.Post, $@"
/v1/swarm/announce
");

        return await SendAsync<object>(req, ct);

    }



    /// <summary><c>GET /v1/swarm/peers</c></summary>

    public async Task<IReadOnlyList<Models.PeerInfo>> SwarmPeers(CancellationToken ct = default)

    {

        using var req = new HttpRequestMessage(HttpMethod.Get, $@"
/v1/swarm/peers
");

        return await SendAsync<IReadOnlyList<Models.PeerInfo>>(req, ct);

    }



    /// <summary><c>POST /v1/swarm/mount/{publicKey}</c></summary>

    public async Task<object> SwarmMount(string publicKey, CancellationToken ct = default)

    {

        using var req = new HttpRequestMessage(HttpMethod.Post, $@"
/v1/swarm/mount/{publicKey}
");

        return await SendAsync<object>(req, ct);

    }



    /// <summary><c>POST /v1/swarm/unmount/{publicKey}</c></summary>

    public async Task<object> SwarmUnmount(string publicKey, CancellationToken ct = default)

    {

        using var req = new HttpRequestMessage(HttpMethod.Post, $@"
/v1/swarm/unmount/{publicKey}
");

        return await SendAsync<object>(req, ct);

    }



    /// <summary><c>GET /v1/identity</c></summary>

    public async Task<Models.IdentityInfo> Identity(CancellationToken ct = default)

    {

        using var req = new HttpRequestMessage(HttpMethod.Get, $@"
/v1/identity
");

        return await SendAsync<Models.IdentityInfo>(req, ct);

    }


    public struct Unit { }
}
