// <auto-generated />
using System;
using Cinereel.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cinereel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CinereelDbContext))]
    [Migration("20260820135548_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Cinereel.Features.Drive.DriveCreationOperationEntity", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("CompensationAttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentTypeId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DriveId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("State");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdempotencyKey");

                    b.HasIndex("DriveId")
                        .IsUnique();

                    b.ToTable("DriveCreationOperations", (string)null);
                });

            modelBuilder.Entity("Cinereel.Features.Drive.DriveEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentTypeId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Drives", (string)null);
                });

            modelBuilder.Entity("Cinereel.Features.Drive.DriveOwnershipEntity", b =>
                {
                    b.Property<Guid>("DriveId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("DriveId");

                    b.ToTable("DriveOwnerships", (string)null);
                });

            modelBuilder.Entity("Cinereel.Features.Drive.DriveOwnershipEntity", b =>
                {
                    b.HasOne("Cinereel.Features.Drive.DriveEntity", "Drive")
                        .WithOne("Ownership")
                        .HasForeignKey("Cinereel.Features.Drive.DriveOwnershipEntity", "DriveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drive");
                });

            modelBuilder.Entity("Cinereel.Features.Drive.DriveEntity", b =>
                {
                    b.Navigation("Ownership");
                });
#pragma warning restore 612, 618
        }
    }
}
